// <auto-generated />
using System;
using Catalog.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260513101251_AddCatalogUniquenessIndexes")]
    partial class AddCatalogUniquenessIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e101"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Everyday consumer electronics and accessories.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TechGear"
                        },
                        new
                        {
                            Id = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e102"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Audio products for work and travel.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SoundCore"
                        },
                        new
                        {
                            Id = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e103"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Inactive supplier used for unavailable product scenarios.",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "LegacyLine"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e201"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Electronic devices and peripherals.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e202"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Smartphones and mobile devices.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Phones",
                            ParentCategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e201")
                        },
                        new
                        {
                            Id = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e203"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Computer and mobile accessories.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accessories",
                            ParentCategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e201")
                        },
                        new
                        {
                            Id = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e204"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Inactive category used for unavailable product scenarios.",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Clearance"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e301"),
                            BrandId = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e101"),
                            CategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e203"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Compact wireless mouse with USB receiver.",
                            IsDeleted = false,
                            Name = "Wireless Mouse",
                            Price = 799.90m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e302"),
                            BrandId = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e102"),
                            CategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e203"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Over-ear Bluetooth headphones with active noise cancellation.",
                            IsDeleted = false,
                            Name = "Noise Cancelling Headphones",
                            Price = 3499.00m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e303"),
                            BrandId = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e101"),
                            CategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e203"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Archived product used to verify non-purchasable product status.",
                            IsDeleted = false,
                            Name = "Mechanical Keyboard",
                            Price = 2199.00m,
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e304"),
                            BrandId = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e103"),
                            CategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e203"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Active product under an inactive brand.",
                            IsDeleted = false,
                            Name = "Legacy Fast Charger",
                            Price = 499.00m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e305"),
                            BrandId = new Guid("a1f08f2b-9b5f-41a0-bc86-bb1131a6e101"),
                            CategoryId = new Guid("b2f08f2b-9b5f-41a0-bc86-bb1131a6e204"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            Description = "Active product under an inactive category.",
                            IsDeleted = false,
                            Name = "Clearance USB-C Cable",
                            Price = 149.90m,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f08f2b-9b5f-41a0-bc86-bb1131a6e501"),
                            AltText = "Black wireless mouse",
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            ImageUrl = "https://cdn.marketplace.local/catalog/wireless-mouse-black.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e301"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("e5f08f2b-9b5f-41a0-bc86-bb1131a6e502"),
                            AltText = "Noise cancelling headphones",
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            ImageUrl = "https://cdn.marketplace.local/catalog/noise-cancelling-headphones.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e302"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Sku")
                        .IsUnique();

                    b.ToTable("product_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e401"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "Black",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e301"),
                            Sku = "WM-BLK",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e402"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "White",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e301"),
                            Sku = "WM-WHT",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e403"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "Black",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e302"),
                            Sku = "NCH-BLK",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e404"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "Silver",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e302"),
                            Sku = "NCH-SLV",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e405"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "TR Layout",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e303"),
                            Sku = "MK-TR",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e406"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "65W",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e304"),
                            Sku = "LFC-65W",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d4f08f2b-9b5f-41a0-bc86-bb1131a6e407"),
                            CreatedAtUtc = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "catalog-seed",
                            IsDeleted = false,
                            Name = "1m",
                            ProductId = new Guid("c3f08f2b-9b5f-41a0-bc86-bb1131a6e305"),
                            Sku = "CUC-1M",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Category", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
